helloworld/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
	# URL padrão
    path('', include('website.urls', namespace='website')),

    # Interface administrativa
    path('admin/', admin.site.urls),
]

website/urls.py
from website.views import IndexTemplateView, FuncionarioListView, FuncionarioUpdateView, FuncionarioCreateView, \
    FuncionarioDeleteView

from django.urls import path

app_name = 'website'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /funcionario/cadastrar
    path('funcionario/cadastrar', FuncionarioCreateView.as_view(), name="cadastra_funcionario"),

    # GET /funcionarios
    path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),
]

helloworld/models.py
from django.db import models


class Funcionario(models.Model):

    nome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    sobrenome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    cpf = models.CharField(
        max_length=14,
        null=False,
        blank=False
    )

    tempo_de_servico = models.IntegerField(
        default=0,
        null=False,
        blank=False
    )

    remuneracao = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=False,
        blank=False
    )

    objetos = models.Manager()

website/forms.py
from helloworld.models import Funcionario
from django import forms


# FORMULÁRIO DE INCLUSÃO DE FUNCIONÁRIOS
# -------------------------------------------

class InsereFuncionarioForm(forms.ModelForm):

    chefe = forms.BooleanField(
        label='Chefe?',
        required=False,
    )

    biografia = forms.CharField(
        label='Biografia',
        required=False,
        widget=forms.Textarea
    )

    class Meta:
        # Modelo base
        model = Funcionario

        # Campos que estarão no form
        fields = [
            'nome',
            'sobrenome',
            'cpf',
            'tempo_de_servico',
            'remuneracao'
        ]

website/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from helloworld.models import Funcionario
from website.forms import InsereFuncionarioForm


# PÁGINA PRINCIPAL
# ----------------------------------------------

class IndexTemplateView(TemplateView):
    template_name = "website/index.html"


# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioListView(ListView):
    template_name = "website/lista.html"
    model = Funcionario
    context_object_name = "funcionarios"


# CADASTRAMENTO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioCreateView(CreateView):
    template_name = "website/cria.html"
    model = Funcionario
    form_class = InsereFuncionarioForm
    success_url = reverse_lazy("website:lista_funcionarios")


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioUpdateView(UpdateView):
    template_name = "website/atualiza.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("website:lista_funcionarios")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioDeleteView(DeleteView):
    template_name = "website/exclui.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("website:lista_funcionarios")

website/templates/website/atualiza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Página de Atualização de Funcionário</h1>

    <ul>
        <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
        <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
        <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
    </ul>

    <form method="post">
        <!-- É necessário colocar o código abaixo em toda página que                   -->
        <!-- contenha um formulário para evitar o ataque de Cross Site Request Forgery -->
        {% csrf_token %}

        {{ form }}

        <button>Enviar</button>
    </form>
</body>
</html>

website/templates/website/cria.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Página de Inserção de Funcionário</h1>

    <ul>
        <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
        <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
        <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
    </ul>

    <form method="post">
        <!-- É necessário colocar o código abaixo em toda página que                   -->
        <!-- contenha um formulário para evitar o ataque de Cross Site Request Forgery -->
        {% csrf_token %}

        {{ form }}

        <button>Enviar</button>
    </form>
</body>
</html>

website/templates/website/exclui.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Página de Exclusão de Funcionário</h1>

    <ul>
        <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
        <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
        <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
    </ul>

    <form method="post" style="border: 1px solid #AAA; margin: 64px auto; padding: 32px; width: 50%;">
        <!-- É necessário colocar o código abaixo em toda página que                   -->
        <!-- contenha um formulário para evitar o ataque de Cross Site Request Forgery -->
        {% csrf_token %}

        Você tem certeza que quer excluir o funcionário <b>{{ funcionario.nome }}</b>? <br><br>

        <button type="button">
            <a href="{% url 'website:lista_funcionarios' %}">Cancelar</a>
        </button>
        <button>Excluir</button>
    </form>
</body>
</html>

website/templates/website/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Página Inicial</h1>

    <ul>
        <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
        <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
        <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
    </ul>
</body>
</html>

website/templates/website/lista.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Lista de Funcionários</h1>

    <ul>
        <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
        <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
        <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
    </ul>

    <div style="max-width: 50%;">
        <table style="border: 1px solid #BBB; width: 100%;">
            <thead>
                <tr style="border-bottom: 1px solid #AAA">
                    <td><b>Nome</b></td>
                    <td><b>CPF</b></td>
                    <td><b>Remuneração</b></td>
                    <td><b>Tempo de Serviço</b></td>
                    <td><b>Ações</b></td>
                </tr>
            </thead>

            <tbody>
                {% for funcionario in funcionarios %}
                    <tr>
                        <td>{{ funcionario.nome }} {{ funcionario.sobrenome }}</td>
                        <td>{{ funcionario.cpf }}</td>
                        <td>{{ funcionario.remuneracao }}</td>
                        <td>{{ funcionario.tempo_de_servico }}</td>
                        <td><a href="{% url 'website:atualiza_funcionario' pk=funcionario.id %}">Atualizar</a></td>
                        <td><a href="{% url 'website:deleta_funcionario' pk=funcionario.id %}">Excluir</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>